# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://blog.rdtr.net/"

languageCode = "ja"
title = "Your Mileage May Vary"
theme = "one"
googleAnalytics = "UA-123-45"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["archives.md", "about.md"]

[permalinks]
  posts = "/:year/:month/:slug/"